import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Barr from "@/components/Navbars/Barr";
import Navbar from "@/components/Navbars/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar user="Yahyawi Amine" role="CEO"/>
        <Barr name="Sprint 02" />
        {children}
      </body>
    </html>
  );
}
